services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo_db_password
    user: odoo

  db:
    image: postgres:9.4
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo_db_password
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
      - ./backups:/backups
    user: "${UID}:${GID}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-restore:
    image: postgres:9.4
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backups:/backups
    user: "${UID}:${GID}"
    environment:
      - PGHOST=db
      - PGUSER=odoo
      - PGPASSWORD=odoo_db_password
      - PGDATABASE=postgres
    command: >
      bash -c "if [ -f /backups/db_backup.sql ]; then
                 echo 'Restoring database...';
                 psql -f /backups/db_backup.sql;
                 echo 'Database restored.';
               else
                 echo 'No backup file found. Skipping restore.';
               fi"

volumes:
  odoo-web-data:
  odoo-db-data: